apiVersion: v1
kind: PersistentVolume
metadata:
  name: rtsp-pv
spec:
  storageClassName: rtsp-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.4
    path: "/mnt/ed2/rtsp-app"
    readOnly: false

